version: '3'

services:
  fpl-data-loader:
    build:
      context: .
      dockerfile: ./fpl_data_loader/Dockerfile
    volumes:
      - ./.env:/app/.env
    restart: unless-stopped

  mcp-server:
    build:
      context: .
      dockerfile: ./mcp_server/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/app/.env
    depends_on:
      - fpl-data-loader
    restart: unless-stopped

